= Valavan Rajarajan - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Duty Planner

---

== Overview

Duty Planner is a desktop application used to organise and plan duties for army personnel with various functions for commanders as well as duty personnel. The user interacts with it using a CLI, and it has a GUI created with JavaFX. It is written in Java, and has about 10kLoC


== Summary of contributions

* *Major enhancement*: Added Block Date Command
** What it does: Allows the user to block dates of duty for the upcoming month allowing them not to be scheduled for duties on those particular days
** Justification: This features allows personnel to have some flexibility on the days the do duties and to ensure that they can attend other events or not do duties when they are busy 
** Highlights: This enhancement affected the scheduling algorithm and the algorithm and Duty system had to be modified to allow personnel to block Dates
** Credits: Thanks to my other group members for helping to figure out the block date command

* *Minor enhancement*: Added a command to view blocked Dates

* *Code contributed*: [https://github.com[Functional code]] [https://github.com[Test code]] _{give links to collated code files}_

* *Other contributions*:

** Project management:
*** Managed milestones and issue tracker for the project
** Enhancements to existing features:
*** Edited the person class with NRIC and Rank (Pull requests https://github.com/CS2103-AY1819S2-W15-4/main/pull/31[#31], )
** Documentation:
*** Did cosmetic tweaks to existing contents of the User Guide to modify it to a Duty Planner
** Community:
*** PRs reviewed (with non-trivial review comments): 
*** Reported bugs and suggestions for other teams in the class (examples:  https://github.com[1], https://github.com[2], https://github.com[3])
** Tools:
*** Integrated Codacy and Appveyor to the team repo

_{you can add/remove categories in the list above}_

== Contributions to the User Guide
|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===


== Contributions to the Developer Guide
|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===
