= Pan Yongjing - Project Portfolio
:site-section: AboutUs
:imagesDir: ../images
:stylesDir: ../stylesheets

== PROJECT: Duty Planner

---

== Overview

MINDEF Duty Planner is a desktop application used to help military units in the Singapore Armed Forces organise and plan monthly duties for their servicemen. It has various features and functions for administrator (i.e. commander) as well as the duty personnel (i.e. servicemen). The user interacts with the application using a Command Line Interface (CLI) with a Graphic User Interface (GUI) created with JavaFX. It is written in Java, and has about 10kLoC.

The Duty Planner is modified and upgraded from SE-EDU Address Book 4.

== Summary of contributions

* *Major enhancement*: Creation of the duty package module
** What it does: The duty package consists of classes (i.e. Duty, DutyMonth, DutySettings, DutyStorage) responsible for setting up the duties of a month and assigning them to persons, as well as contains vital functions needed for the duty features to be implemented.
*** `Duty` : A class that characterizes the attributes of a duty including the exact date, points awarded, manpower needed and a list of person eventually being assigned to that duty.
*** `DutyMonth` : Represents a month in the calendar and is the main driver class behind the scheduling of duties. It instantiates all duties and assigns each duty to persons. Stores vital information such as the list of scheduled duties and the blocked dates of each person.
*** `DutySettings` : Contains information about the manpower needed and points assigned to duties based the day of the week. Enable modification to the the manpower needed and points assigned to each duty based on the day of the week.
*** `DutyStorage` : Accumulates and stores the duty points and duty records of all the persons.
** Justification: The duty package provides the backend support for all duty-related features and commands.
** Highlights: The package contain functions assessed by many commands (i.e. BlockDateCommmand, ScheduleCommand, DutySettingsCommand, ViewCommand, PointsCommand, RewardCommand, PenalizeCommand).
** Credits: {Teammate Yoon Ki Hyun for working together on the DutyMonth and Duty}

* *Major enhancement*: `ScheduleCommand` and `ConfirmScheduleCommand`
** What it does: The schedule command that invokes the schedule algorithm to generate a viable duty allocation for the upcoming month. The confirm command finalizes the schedule and updates the existing duty points of each person.
** Justification: Enable duties to be created and scheduled.
** Highlights: The main feature of the application.

* *Major enhancement*: `SettingsCommand`
** What it does: Enable the administrator to adjust the desired manpower for duties based on the day of the week. Enable the administrator to adjust the points to be awarded for doing duties based on the duty of the week.
** Justification: Allows the administrator to have flexibility to change the duty allocation system.
** Highlights: Need to ensure that the scheduling algorithm is compatible with adjustable duty points and duty capacities.

* *Major enhancement*: `PointsCommand`
** What it does: Enable the administrator to view duty points and duty records of all persons.
** Justification: Allows more duty-related information to be viewed.

* *Major enhancement*: `RewardCommand` and `PenalizeCommand`
** What it does: Enable the administrator to reward and penalize points from a person or a list of persons.
** Justification: Allows the administrator the autonomy to manually update duty points.
** Highlight: Enabled us to better test the effectiveness of the scheduling algorithm in obscure situations (i.e. one person having points significantly higher or lower points than the rest).

* *Minor enhancement*: Storage for `DutyStorage` -- `JsonAdaptedDutyStorage`
** What it does: Ensures that duty points and duty records are saved in the system when the application closes.
** Justification: This allows users to open the application with previously saved duty information instead of resetting each time the application reopens.

* *Minor enhancement*: `DateUtil` Common
** What it does: A class that contains static methods to assist in validation of date parameters and other date related functions.
** Justification: Contains commonly used functions that aids the developers and prevent duplicate codes.

* *Code contributed*: [https://nus-cs2103-ay1819s2.github.io/cs2103-dashboard/#search=yjpan47&sort=displayName&since=2019-02-10&until=2019-04-03&timeframe=day&reverse=false&repoSort=true[Code]]

* Project management:
** Managed releases `v1.1`

* Documentation:
** Major updates to the User Guide: +
https://github.com/yjpan47/main/blob/master/docs/UserGuide.adoc
** Updated Developer Guide to include Duty Package: +
https://github.com/yjpan47/main/blob/master/docs/DeveloperGuide.adoc


== Contributions to the User Guide


|===
|_Given below are sections I contributed to the User Guide. They showcase my ability to write documentation targeting end-users._
|===

include::../UserGuide.adoc[tag=pointsAdmin]

include::../UserGuide.adoc[tag=rewardAdmin]

include::../UserGuide.adoc[tag=penalizeAdmin]

include::../UserGuide.adoc[tag=settingsAdmin]

include::../UserGuide.adoc[tag=scheduleAdmin]

include::../UserGuide.adoc[tag=confirmAdmin]

== Contributions to the Developer Guide

|===
|_Given below are sections I contributed to the Developer Guide. They showcase my ability to write technical documentation and the technical depth of my contributions to the project._
|===

include::../DeveloperGuide.adoc[tag=dutyDiagram]

include::../DeveloperGuide.adoc[tag=dutyMonth]

include::../DeveloperGuide.adoc[tag=duty]

include::../DeveloperGuide.adoc[tag=dutyStorage]

include::../DeveloperGuide.adoc[tag=dutySettings]

include::../DeveloperGuide.adoc[tag=scheduleCommand]

include::../DeveloperGuide.adoc[tag=scheduleAlgorithm]

include::../DeveloperGuide.adoc[tag=dutyAlternative]

include::../DeveloperGuide.adoc[tag=scheduleManualTest]

include::../DeveloperGuide.adoc[tag=confirmScheduleManualTest]

include::../DeveloperGuide.adoc[tag=rewardManualTest]

include::../DeveloperGuide.adoc[tag=penalizeManualTest]

include::../DeveloperGuide.adoc[tag=settingsManualTest]

== PROJECT: PowerPointLabs

---
