= Duty Planner - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/cs2103-ay1819s2-w15-4/main

By: `CS2103 W15-4`      Since: `Feb 2019`      Licence: `MIT`

== Introduction

DutyPlanner is optimized for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI). It is a software designed to automate the process of assigning guard duties for soldiers in the Singapore Armed Forces, so that the commanders no longer have to manually assign the dates.

== Quick Start

.  Ensure you have Java version `9` or later installed in your Computer.
.  {To be added}

.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* *`list`* : lists all contacts
* **`add`**`n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01` : adds a contact named `John Doe` to the Address Book.
* **`delete`**`3` : deletes the 3rd contact shown in the current list
* *`exit`* : exits the app

.  Refer to <<Features>> for details of each command.

[[Features]]
== User Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `login nr/NRIC`, `NRIC` is a parameter which can be used as `add n/S01234567Z`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.
====

=== Viewing help : `help`

Lists out a list of commands & instructions +
Format: `help`

=== Log in : `login` `Not implemented yet`

Log user into their account. +
NRIC and password are case-sensitive. +
Format: `login nr/NRIC pw/PASSWORD`

Example:

* `login n/S01234567Z pw/cs2103noteasy`

=== Log out : `logout` `Not implemented yet`
Logs the user out of the account +
Format : `logout`

=== Change password : `chpass` `Not implemented yet`
Changes password of the user to a new one. The system will prompt the user to reconfirm the new password. +
Format: `chpass pw/CURRENT_PASSWORD pw/NEW_PASSWORD

Example:

* `chpass pw/cs2103noteasy pw/cs2103veryhard`

=== View duties assigned to user : `view` `Not implemented yet`
The user can see their details about their own duties assigned to them and their upcoming duties ranked by recency. +
Format: `view`

=== View duties assigned to other users : `view` `Not implemented yet`
The user can see their details about their own duties assigned to other users. +
Format: `view NAME`

Example:

* `view Cassell`

=== View roster : `roster` `Not implemented yet`
The user can see the full duty rosters for particular months. +
Format: `roster MONTH`

Example:

* `roster February`

=== Block dates : `block`
The user can block dates and set which dates they are unavailable to duties for upcoming months. A user can block up to 15 days per month. +
Format: `block MONTH DAY DAY DAY ...`

Example:

* `block March 3 6 15 21 30`

=== View blocked dates : `block`
The user can view the dates they have blocked for a particular month. +
Format: `block MONTH`

Example:

* `block March`

=== Find who is assigned duty today : `who`
The user can find out which person is assigned duty today. +
Format: `who`

=== Find who is assigned duty on a given day : `who`
The user can find out which person is assigned duty on a given day. +
Format: `who DATE`

Example:

* `who 14022019`

=== Make a swap request with another user : `swap`
The user can request for a duty swap with another user. This will be subject to the agreement of the other user and approval of the admin (i.e. commander). +
The other user and admin will be notified upon login and they will be prompted to accept or decline the request. +
Format: `swap d/CURRENTDUTYDATE d/DESIREDDUTYDATE [t/MESSAGE]

Example:

* `swap d/14022019 d/21022019 t/Please help a bro out!`

=== Finding another person: `find`
The user can find people whose names contain any of the given keywords. Information of the person’s rank. company, section and contact number can be seen. +
Format: `find KEYWORD [MORE KEYWORDS]`

=== Filter people: `filter`
The user can list out the people who are within the filtered rank, date, or company. The list can be sorted in ascending or descending order. +
Format: `filter [A or D] [s/STARTDATE] [e/ENDDATE] [r/RANK] [c/COMPANY] [s/SQUAD]`

====
* Default ordering is alphabetical order, ascending
* A or D specifies if ordering is ascending or descending
* Dates to be entered in ddmmyyyy format.
====

Examples:

* `filter` +
Lists down all personnel, without any filtering, sorted in ascending order by default

* `filter D s/11022019 e/11032019 r/PTE` +
Lists down all personnel with rank Private and available dates between 11-Feb-2019 and 11-March-2019, in descending alphabetical order.

=== Exit : `exit`
Exits the program. User will be logged out automatically. +
Format: `exit`

== Admin Features

=== Viewing help for admin : `helpadmin`
Lists out a list of commands & instructions for admin. +
Format: `helpadmin`

=== Add a user : `add`
Add a user to the system with the corresponding NRIC, password, company, section, rank, name and contact number. +
Format: `add nr/NRIC pw/PASSWORD c/COMPANY s/SECTION r/RANK n/NAME p/CONTACTNUMBER`

=== Delete a user : `delete`
Delete a user from the system with the corresponding NRIC. The admin will be prompted with a confirmation message. +
Format: `delete nr/NRIC`

=== Update a user’s details : `edit`
Updates a existing user’s details given an NRIC. +
Format: `edit [nr/NRIC] [c/COMPANY] [s/SECTION] [r/RANK] [n/NAME] [p/PHONENUMBER]`

=== Import personal details from a file : `import`
Imports personal details of users from a TXT file. +
Format: `import [FILE_NAME.txt]`

=== List all the users: `list`
Lists out all users in the system with their details. +
Format: `list`

=== Scheduling duties : `schedule`
This command schedules the duties for the upcoming month. It takes into account the block out dates of each guard duty personnel and their extras. It will sort by available dates and distribute duties accordingly. After the algorithm computes a plausible schedule, the schedule will be displayed and admin will be prompted to either confirm the schedule or rerun the scheduler algorithm. +
Format: `schedule MONTH`

=== Extra duty : `extra`
Automatically allocates extra duties for a selected personnel in the upcoming month. +
Format: `extra nr/NRIC d/NUMBEROFDAYS`

Example:

*`extra n/S9876543A d/7`

=== Saving the data

Duty roster data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

== FAQ

*Q*: What if I want to swap my duty with another person? +
*A*: Contact the administrator with the request.

*Q*: What is the main feature of this app? +
*A*: The main feature is the automated scheduling algorithm, which significantly minimizes the amount of work that +
the admin has to do.

*Q*: What is my username and password? +
*A*: Your username is by default your NRIC, used so prevalently in the SAF. +
Your password will be set by the admin when they create your account but you can change the password later on +
using the chpass command.

*Q*: What should I do if I need help with the app? +
*A*: You can enter 'help' in the command line, or press Help > Help, or simply press F1. +
This will open up the User Guide in a new window.

*Q*: What's the difference between 'add' and 'import'? +
*A*: 'Add' is only able to add one user at a time and requires all the details of the user on +
the command line. This is very cumbersome for the admin so we added an 'import' command that reads a +
.txt file containing multiple user details, with the same parameters format as the 'add' command.

== Command Summary
General User +
* *Viewing help* : `help` +
* *Log in* : `login nr/NRIC  pw/PASSWORD` +
* *Log out* : `logout` +
* *View* : `view KEYWORD [MORE KEYWORDS]` +
* *Blocking dates* : `block d/date d/date d/date …` +
* *Finding a person* : `find KEYWORD [MORE KEYWORDS]` +
* *Filter* : `filter [A or D] [s/STARTDATE] [e/ENDDATE] [r/RANK] [c/COMPANY] [s/SQUAD]` +
* *Change password* : `chpass pw/CURRENT_PASSWORD pw/NEW_PASSWORD` +
* *Exit* : `exit` +
Admin +
* *Command help for admin* : `helpAdmin` +
* *Add a user* : `addUser nr/NRIC pw/PASSWORD c/COMPANY s/SECTION r/RANK n/NAME p/PHONENUMBER` +
* *Delete a user* : `deleteUser nr/NRIC` +
* *Edit a user* : `editUser [nr/NRIC] [c/COMPANY] [s/SECTION] [r/RANK] [n/NAME] [p/PHONENUMBER]` +
* *Import personal details from a file* : `import [FILE_NAME.txt]` +
* *List all the users* : `listUser` +
* *Scheduling duties* : `schedule m/MONTH` +
