= Duty Planner - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/cs2103-ay1819s2-w15-4/main

By: `CS2103 W15-4`      Since: `Feb 2019`      Licence: `MIT`

== Introduction

MINDEF Duty Planner is a platform to assist military units in the SAF in the assignment of daily duties amonst the servicemen. The application is optimized for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI). The software is designed to automate the process of fairly assigning duties to available servicemen for an entire month. It also enables servicemen to conveniently indicate the days they are unavailable for duty. It seeks to fairly distribute duties by taking into account the varying importance of each duty (e.g. Sunday duties are worth more than weekday duties). 

== Quick Start

.  Ensure you have Java version `9` or later installed in your Computer.
.  {To be added}

.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* *`list`* : lists all contacts
* **`add`**`n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01` : adds a contact named `John Doe` to the Address Book.
* **`delete`**`3` : deletes the 3rd contact shown in the current list
* *`exit`* : exits the app

.  Refer to <<Features>> for details of each command.
.  Some commands can only be accessed by Admin type accounts and some by General type accounts.

[[Features]]
== User Features

=== Log in
Logs user into account +
NRIC and passwords are case-sensitive. +
By default, if your password has not been changed by you or an Admin, the password is your NRIC. +
Can only be done in the login box at the start of the program. +
Enter in NRIC and password into the top and bottom text areas respectively, press enter. +
Contact an administrator if you have trouble logging in. +
If you need to change your account, exit the program, then log back into a different account.

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `login nr/NRIC`, `NRIC` is a parameter which can be used as `add n/S01234567Z`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.
* An Admin and a User may have different formats for the same command
====

=== Features for all users

==== Viewing help : `help`

Lists out a list of commands & instructions +
Format: `help`


==== List all the users: `list`
Lists out all users in the system with their details. +
Brings up view of the person list.+
Format: `list`

==== View duties assigned to user : `view` `Not implemented yet`
The user can see their details about their own duties assigned to them and their upcoming duties ranked by recency. +
Format: `view`

==== View duties assigned to other users : `view` `Not implemented yet`
The user can see their details about their own duties assigned to other users. +
Format: `view NAME`

Example:

* `view Cassell`

==== View roster : `roster` `Not implemented yet`
The user can see the full duty rosters for particular months. +
Format: `roster MONTH`

Example:

* `roster February`

==== Block dates : `block`
The user can block dates and set which dates they are unavailable to duties for upcoming months. A user can block up to 15 days per month. +
Format: `block MONTH DAY DAY DAY ...`

Example:

* `block March 3 6 15 21 30`

==== View blocked dates : `block`
The user can view the dates they have blocked for a particular month. +
Format: `block MONTH`

Example:

* `block March`

==== Find who is assigned duty today : `who`
The user can find out which person is assigned duty today. +
Format: `who`

==== Find who is assigned duty on a given day : `who`
The user can find out which person is assigned duty on a given day. +
Format: `who DATE`

Example:

* `who 14022019`

==== Make a swap request with another user : `swap`
The user can request for a duty swap with another user. This will be subject to the agreement of the other user and approval of the admin (i.e. commander). +
The other user and admin will be notified upon login and they will be prompted to accept or decline the request. +
Format: `swap d/CURRENTDUTYDATE d/DESIREDDUTYDATE [t/MESSAGE]

Example:

* `swap d/14022019 d/21022019 t/Please help a bro out!`

==== Finding another person: `find`
The user can find people whose names contain any of the given keywords. Information of the person’s rank. company, section and contact number can be seen. +
Format: `find KEYWORD [MORE KEYWORDS]`

==== Filter people: `filter`
The user can list out the people who are within the filtered rank, date, or company. The list can be sorted in ascending or descending order. +
Format: `filter [A or D] [s/STARTDATE] [e/ENDDATE] [r/RANK] [c/COMPANY] [s/SQUAD]`

====
* Default ordering is alphabetical order, ascending
* A or D specifies if ordering is ascending or descending
* Dates to be entered in ddmmyyyy format.
====

Examples:

* `filter` +
Lists down all personnel, without any filtering, sorted in ascending order by default

* `filter D s/11022019 e/11032019 r/PTE` +
Lists down all personnel with rank Private and available dates between 11-Feb-2019 and 11-March-2019, in descending alphabetical order.

==== Exit : `exit`
Exits the program. User will be logged out automatically. +
Format: `exit`

=== General Features

==== Edit user details : `edit`
Edits user details. Can edit one or more fields, but not the NRIC or the account type. +
Format: `edit [c/COMPANY] [s/SECTION] [r/RANK] [n/NAME] [p/PHONE] [t/TAG] [pw/PASSWORD]`

=== Admin Features

// tag::adddelete[]
==== Add a user : `add`
Add a user to the system with the corresponding NRIC, password, company, section, rank, name and contact number. +
By default, the user will be a General type account, and the password will be the NRIC. +
Format: `add nr/NRIC c/COMPANY s/SECTION r/RANK n/NAME p/PHONE [t/TAG]`


==== Delete a user : `delete`
Delete a user based on the index in the list+
Format: `delete INDEX`
// end::adddelete[]

==== Edit a user’s details : `edit`
Edits an existing user’s details based on the index number in the list. Can edit one or more fields. +
For account type field, A corresponds to an Admin account, G corresponds to a general account.
Format: `edit INDEX [nr/NRIC] [c/COMPANY] [s/SECTION] [r/RANK] [n/NAME] [p/PHONE] [t/TAG] [pw/PASSWORD] [u/A or G]`

==== Import personal details from a file : `import`
Imports personal details of users from a TXT file. +
Format: `import [FILE_NAME.txt]`



=== Scheduling duties : `schedule`
This command invokes the scheduling algorithm for the upcoming month. It generates a viable duty schedule roster where each duty slot for the upcoming month will be filled by the people currently in the database. ++

.In order to ensure fair scheduling system,
. We introduce a point system to each individual such that a servivemen can earn points by doing duties. The points awarded to servicemen are cumulative, thus the points awarded are carried over to the next month. +
. Each duty is worth a certain number of points and a person gains that amount of points by doing that duty. For example, if all Sunday duties are worth 4 points, a servicemen who is assigned a Sunday duty will by awarded 4 points. +
. Before the scheuling command is called, each person has the opportunity to indicate the days in which they are unavilable to do duty. (See 3.9 block command)  +


The algorithm is optimized such that persons with low points will be allocated to duties with high points. It automatically attempts to balance out the points of each person by the end of the month. +

The duty schedule generated by the schedule command is not deterministic, calling schedule command multiple times generates different duty allocation. +

Calling the schedule command merely generates a viable shedule, but does not finalize the schedule (i.e. points awarded to each person is yet to be added). Schedule generated is also not deterministic, calling schedule command multiple times generates different duty allocation. Thus, the admin can call schedule command continuously until a satisfactory schedule is produced. To finalize the schedule, use the confirm command. (See 4.8 confirm schedule) +

Format: `schedule`

=== Confirm a Schedule : `confirm`
Confirm and finalize the last generated duty schedule (from the schedule command) for the upcoming month. +
Subsequent attempts to call schedule command will not result in any new duty allocation produced. +
Format: `confirm`

=== Saving the data

Duty roster data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

== FAQ

*Q*: What if I want to swap my duty with another person? +
*A*: Contact the administrator with the request.

*Q*: What is the main feature of this app? +
*A*: The main feature is the automated scheduling algorithm, which significantly minimizes the amount of work that +
the admin has to do.

*Q*: What is my username and password? +
*A*: Your username is by default your NRIC, used so prevalently in the SAF. +
Your password will be set by the admin when they create your account but you can change the password later on +
using the chpass command.

*Q*: What should I do if I need help with the app? +
*A*: You can enter 'help' in the command line, or press Help > Help, or simply press F1. +
This will open up the User Guide in a new window.

*Q*: What's the difference between 'add' and 'import'? +
*A*: 'Add' is only able to add one user at a time and requires all the details of the user on +
the command line. This is very cumbersome for the admin so we added an 'import' command that reads a +
.txt file containing multiple user details, with the same parameters format as the 'add' command.

== Command Summary
General User +
* *Viewing help* : `help` +
* *View* : `view KEYWORD [MORE KEYWORDS]` +
* *Blocking dates* : `block d/date d/date d/date …` +
* *Finding a person* : `find KEYWORD [MORE KEYWORDS]` +
* *Filter* : `filter [A or D] [s/STARTDATE] [e/ENDDATE] [r/RANK] [c/COMPANY] [s/SQUAD]` +
* *Edit* : `edit [c/COMPANY] [s/SECTION] [r/RANK] [n/NAME] [p/PHONE] [t/TAG] [pw/PASSWORD]` +
* *Exit* : `exit` +
Admin +
* *Add a user* : `addUser nr/NRIC c/COMPANY s/SECTION r/RANK n/NAME p/PHONE [t/TAG] +
* *Edit a user* : `edit INDEX [nr/NRIC] [c/COMPANY] [s/SECTION] [r/RANK] [n/NAME] [p/PHONE] [t/TAG] [pw/PASSWORD] [u/A or G]` +
* *Import personal details from a file* : `import [FILE_NAME.txt]` +
* *List all the users* : `listUser` +
* *Scheduling duties* : `schedule m/MONTH` +
