= AddressBook Level 4 - User Guide
:site-section: UserGuide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:stylesDir: stylesheets
:xrefstyle: full
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]
:repoURL: https://github.com/cs2103-ay1819s2-w15-4/main

By: `CS2103 W15-4`      Since: `Feb 2019`      Licence: `MIT`

== Introduction

DutyPlanner is optimized for those who prefer to work with a Command Line Interface (CLI) while still having the benefits of a Graphical User Interface (GUI). It is a software designed to automate the process of assigning guard duties for soldiers in the Singapore Armed Forces, so that the commanders no longer have to manually assign the dates.

== Quick Start

.  Ensure you have Java version `9` or later installed in your Computer.
.  {To be added}

.  Type the command in the command box and press kbd:[Enter] to execute it. +
e.g. typing *`help`* and pressing kbd:[Enter] will open the help window.
.  Some example commands you can try:

* *`list`* : lists all contacts
* **`add`**`n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01` : adds a contact named `John Doe` to the Address Book.
* **`delete`**`3` : deletes the 3rd contact shown in the current list
* *`exit`* : exits the app

.  Refer to <<Features>> for details of each command.

[[Features]]
== Features

====
*Command Format*

* Words in `UPPER_CASE` are the parameters to be supplied by the user e.g. in `login n/NRIC`, `NRIC` is a parameter which can be used as `add n/S01234567Z`.
* Items in square brackets are optional e.g `n/NAME [t/TAG]` can be used as `n/John Doe t/friend` or as `n/John Doe`.
* Items with `…`​ after them can be used multiple times including zero times e.g. `[t/TAG]...` can be used as `{nbsp}` (i.e. 0 times), `t/friend`, `t/friend t/family` etc.
* Parameters can be in any order e.g. if the command specifies `n/NAME p/PHONE_NUMBER`, `p/PHONE_NUMBER n/NAME` is also acceptable.
====

=== Viewing help : `help`

Lists out a list of commands & instructions
Format: `help`

=== Log in : `login` `Not implemented yet`

Log user into their account.
NRIC and password are case-sensitive.
Format: `login n/NRIC pw/PASSWORD`

Example:

* `login n/S01234567Z pw/cs2103noteasy`

=== Log out : `logout` `Not implemented yet`
Logs the user out of the account
Format : `logout`

=== Change password : `chpass` `Not implemented yet`
Changes password of the user to a new one. The system will prompt the user to reconfirm the new password.
Format: `chpass pw/CURRENT_PASSWORD pw/NEW_PASSWORD

Example: 

* `chpass pw/cs2103noteasy pw/cs2103veryhard`

=== View duties assigned to user : `view` `Not implemented yet`
The user can see their details about their own duties assigned to them and their upcoming duties ranked by recency.
Format: `view`

=== View duties assigned to other users : `view` `Not implemented yet`
The user can see their details about their own duties assigned to other users.
Format: `view NAME`

Example:

* `view Cassell`

=== View roster : `roster` `Not implemented yet`
The user can see the full duty rosters for particular months.
Format: `roster MONTH`

Example:

* `roster February`

=== Block dates : `block`
The user can block dates and set which dates they are unavailable to duties for upcoming months. A user can block up to 15 days per month.
Format: `block MONTH DAY DAY DAY ...`

Example:

* `block March 3 6 15 21 30`

=== View blocked dates : `block`
The user can view the dates they have blocked for a particular month.
Format: `block MONTH`

Example:

* `block March`

=== Find who is assigned duty today : `who`
The user can find out which person is assigned duty today.
Format: `who`

=== Find who is assigned duty on a given day : `who`
The user can find out which person is assigned duty on a given day
Format: `who DATE`

Example:

* `who 14022019`

=== Make a swap request with another user : `swap`
The user can request for a duty swap with another user. This will be subject to the agreement of the other user and approval of the admin (i.e. commander).
The other user and admin will be notified upon login and they will be prompted to accept or decline the request. 
Format: `swap d/CURRENTDUTYDATE d/DESIREDDUTYDATE [t/MESSAGE]

Example:

* `swap d/14022019 d/21022019 t/Please help a bro out!`

=== Finding another person: `find`
The user can find people whose names contain any of the given keywords. Information of the person’s rank. company, section and contact number can be seen.
Format: `find KEYWORD [MORE KEYWORDS]`

=== Filter people: `filter`
The user can list out the people who are within the filtered rank, date, or company. The list can be sorted in ascending or descending order. 
Format: `filter [A or D] [s/STARTDATE] [e/ENDDATE] [r/RANK] [c/COMPANY] [s/SQUAD]`

====
* Default ordering is alphabetical order, ascending
* A or D specifies if ordering is ascending or descending
* Dates to be entered in ddmmyyyy format.
====

Examples:

* `filter`
Lists down all personnel, without any filtering, sorted in ascending order by default

* `filter D s/11022019 e/11032019 r/PTE`
Lists down all personnel with rank Private and available dates between 11-Feb-2019 and 11-March-2019, in descending alphabetical order.

=== Exit : `exit`
Exits the program. User will be logged out automatically.
Format: `exit`



=== Adding a person: `add`

Adds a person to the address book +
Format: `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...`

[TIP]
A person can have any number of tags (including 0)

Examples:

* `add n/John Doe p/98765432 e/johnd@example.com a/John street, block 123, #01-01`
* `add n/Betsy Crowe t/friend e/betsycrowe@example.com a/Newgate Prison p/1234567 t/criminal`

=== Listing all persons : `list`

Shows a list of all persons in the address book. +
Format: `list`

=== Editing a person : `edit`

Edits an existing person in the address book. +
Format: `edit INDEX [n/NAME] [p/PHONE] [e/EMAIL] [a/ADDRESS] [t/TAG]...`

****
* Edits the person at the specified `INDEX`. The index refers to the index number shown in the displayed person list. The index *must be a positive integer* 1, 2, 3, ...
* At least one of the optional fields must be provided.
* Existing values will be updated to the input values.
* When editing tags, the existing tags of the person will be removed i.e adding of tags is not cumulative.
* You can remove all the person's tags by typing `t/` without specifying any tags after it.
****

Examples:

* `edit 1 p/91234567 e/johndoe@example.com` +
Edits the phone number and email address of the 1st person to be `91234567` and `johndoe@example.com` respectively.
* `edit 2 n/Betsy Crower t/` +
Edits the name of the 2nd person to be `Betsy Crower` and clears all existing tags.

=== Locating persons by name: `find`

Finds persons whose names contain any of the given keywords. +
Format: `find KEYWORD [MORE_KEYWORDS]`

****
* The search is case insensitive. e.g `hans` will match `Hans`
* The order of the keywords does not matter. e.g. `Hans Bo` will match `Bo Hans`
* Only the name is searched.
* Only full words will be matched e.g. `Han` will not match `Hans`
* Persons matching at least one keyword will be returned (i.e. `OR` search). e.g. `Hans Bo` will return `Hans Gruber`, `Bo Yang`
****

Examples:

* `find John` +
Returns `john` and `John Doe`
* `find Betsy Tim John` +
Returns any person having names `Betsy`, `Tim`, or `John`

=== Deleting a person : `delete`

Deletes the specified person from the address book. +
Format: `delete INDEX`

****
* Deletes the person at the specified `INDEX`.
* The index refers to the index number shown in the displayed person list.
* The index *must be a positive integer* 1, 2, 3, ...
****

Examples:

* `list` +
`delete 2` +
Deletes the 2nd person in the address book.
* `find Betsy` +
`delete 1` +
Deletes the 1st person in the results of the `find` command.

=== Selecting a person : `select`

Selects the person identified by the index number used in the displayed person list. +
Format: `select INDEX`

****
* Selects the person and loads the Google search page the person at the specified `INDEX`.
* The index refers to the index number shown in the displayed person list.
* The index *must be a positive integer* `1, 2, 3, ...`
****

Examples:

* `list` +
`select 2` +
Selects the 2nd person in the address book.
* `find Betsy` +
`select 1` +
Selects the 1st person in the results of the `find` command.

=== Listing entered commands : `history`

Lists all the commands that you have entered in reverse chronological order. +
Format: `history`

[NOTE]
====
Pressing the kbd:[&uarr;] and kbd:[&darr;] arrows will display the previous and next input respectively in the command box.
====

// tag::undoredo[]
=== Undoing previous command : `undo`

Restores the address book to the state before the previous _undoable_ command was executed. +
Format: `undo`

[NOTE]
====
Undoable commands: those commands that modify the address book's content (`add`, `delete`, `edit` and `clear`).
====

Examples:

* `delete 1` +
`list` +
`undo` (reverses the `delete 1` command) +

* `select 1` +
`list` +
`undo` +
The `undo` command fails as there are no undoable commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +

=== Redoing the previously undone command : `redo`

Reverses the most recent `undo` command. +
Format: `redo`

Examples:

* `delete 1` +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +

* `delete 1` +
`redo` +
The `redo` command fails as there are no `undo` commands executed previously.

* `delete 1` +
`clear` +
`undo` (reverses the `clear` command) +
`undo` (reverses the `delete 1` command) +
`redo` (reapplies the `delete 1` command) +
`redo` (reapplies the `clear` command) +
// end::undoredo[]

=== Clearing all entries : `clear`

Clears all entries from the address book. +
Format: `clear`

=== Exiting the program : `exit`

Exits the program. +
Format: `exit`

=== Saving the data

Address book data are saved in the hard disk automatically after any command that changes the data. +
There is no need to save manually.

// tag::dataencryption[]
=== Encrypting data files `[coming in v2.0]`

_{explain how the user can enable/disable data encryption}_
// end::dataencryption[]

== FAQ

*Q*: How do I transfer my data to another Computer? +
*A*: Install the app in the other computer and overwrite the empty data file it creates with the file that contains the data of your previous Address Book folder.

== Command Summary

* *Add* `add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]...` +
e.g. `add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague`
* *Clear* : `clear`
* *Delete* : `delete INDEX` +
e.g. `delete 3`
* *Edit* : `edit INDEX [n/NAME] [p/PHONE_NUMBER] [e/EMAIL] [a/ADDRESS] [t/TAG]...` +
e.g. `edit 2 n/James Lee e/jameslee@example.com`
* *Find* : `find KEYWORD [MORE_KEYWORDS]` +
e.g. `find James Jake`
* *List* : `list`
* *Help* : `help`
* *Select* : `select INDEX` +
e.g.`select 2`
* *History* : `history`
* *Undo* : `undo`
* *Redo* : `redo`
